window.LIFEOS_SEED = {
  "tasks": [
    {
      "id": "T0001",
      "title": "선유 핸드폰 요금제 데이터 종량제로 변경하기",
      "status": "미완료",
      "area": "가족",
      "type": "할일",
      "list": "일반",
      "created_at": "2026-09-04",
      "due_at": "",
      "completed_at": "",
      "delegate": "",
      "note": "",
      "sort_order": 1
    },
    {
      "id": "T0002",
      "title": "드론 충전하기",
      "status": "미완료",
      "area": "집",
      "type": "할일",
      "list": "일반",
      "created_at": "2026-09-07",
      "due_at": "",
      "completed_at": "",
      "delegate": "",
      "note": "",
      "sort_order": 2
    },
    {
      "id": "T0003",
      "title": "침대 이불 빨기",
      "status": "미완료",
      "area": "집",
      "type": "할일",
      "list": "일반",
      "created_at": "2026-09-04",
      "due_at": "",
      "completed_at": "",
      "delegate": "",
      "note": "",
      "sort_order": 3
    },
    {
      "id": "T0004",
      "title": "안 입는 옷 정리하기",
      "status": "미완료",
      "area": "집",
      "type": "할일",
      "list": "일반",
      "created_at": "2026-09-04",
      "due_at": "",
      "completed_at": "",
      "delegate": "",
      "note": "",
      "sort_order": 4
    },
    {
      "id": "T0005",
      "title": "책상 정리하기",
      "status": "미완료",
      "area": "집",
      "type": "할일",
      "list": "일반",
      "created_at": "2026-09-04",
      "due_at": "",
      "completed_at": "",
      "delegate": "",
      "note": "",
      "sort_order": 5
    },
    {
      "id": "T0006",
      "title": "노트북에 지은이 GPT 설치하기",
      "status": "미완료",
      "area": "개인",
      "type": "할일",
      "list": "일반",
      "created_at": "2026-09-07",
      "due_at": "",
      "completed_at": "",
      "delegate": "",
      "note": "",
      "sort_order": 6
    },
    {
      "id": "T0007",
      "title": "앤트로픽 및 OpenAI 관련 ETF 알아보기",
      "status": "미완료",
      "area": "투자",
      "type": "할일",
      "list": "일반",
      "created_at": "2026-09-08",
      "due_at": "",
      "completed_at": "",
      "delegate": "",
      "note": "",
      "sort_order": 7
    },
    {
      "id": "T0008",
      "title": "지호방 조명 정비하기",
      "status": "미완료",
      "area": "집",
      "type": "할일",
      "list": "일반",
      "created_at": "2026-09-22",
      "due_at": "",
      "completed_at": "",
      "delegate": "",
      "note": "",
      "sort_order": 8
    },
    {
      "id": "T0009",
      "title": "테슬라 주차스티커판 준비하기",
      "status": "미완료",
      "area": "차량",
      "type": "할일",
      "list": "일반",
      "created_at": "2026-09-23",
      "due_at": "",
      "completed_at": "",
      "delegate": "",
      "note": "",
      "sort_order": 9
    },
    {
      "id": "T0010",
      "title": "협탁 치우기",
      "status": "미완료",
      "area": "집",
      "type": "할일",
      "list": "일반",
      "created_at": "2026-09-26",
      "due_at": "",
      "completed_at": "",
      "delegate": "",
      "note": "",
      "sort_order": 10
    },
    {
      "id": "T0011",
      "title": "도쿄 책 구매하기",
      "status": "미완료",
      "area": "여행",
      "type": "할일",
      "list": "일반",
      "created_at": "2026-09-26",
      "due_at": "",
      "completed_at": "",
      "delegate": "",
      "note": "",
      "sort_order": 11
    },
    {
      "id": "T0012",
      "title": "옷장 정리하기",
      "status": "미완료",
      "area": "집",
      "type": "할일",
      "list": "일반",
      "created_at": "2026-09-26",
      "due_at": "",
      "completed_at": "",
      "delegate": "",
      "note": "",
      "sort_order": 12
    },
    {
      "id": "T0013",
      "title": "집 안 가구 먼지 제거하기",
      "status": "미완료",
      "area": "집",
      "type": "할일",
      "list": "일반",
      "created_at": "2026-09-26",
      "due_at": "",
      "completed_at": "",
      "delegate": "",
      "note": "",
      "sort_order": 13
    },
    {
      "id": "T0014",
      "title": "팰리 세차하기",
      "status": "미완료",
      "area": "차량",
      "type": "할일",
      "list": "일반",
      "created_at": "2026-09-26",
      "due_at": "",
      "completed_at": "",
      "delegate": "",
      "note": "",
      "sort_order": 14
    },
    {
      "id": "T0015",
      "title": "지호방 청소하기",
      "status": "미완료",
      "area": "집",
      "type": "할일",
      "list": "일반",
      "created_at": "2026-09-26",
      "due_at": "",
      "completed_at": "",
      "delegate": "",
      "note": "",
      "sort_order": 15
    },
    {
      "id": "T0016",
      "title": "BP 원금 회수 후 투자처 찾아보기",
      "status": "미완료",
      "area": "투자",
      "type": "할일",
      "list": "일반",
      "created_at": "2026-09-26",
      "due_at": "",
      "completed_at": "",
      "delegate": "",
      "note": "",
      "sort_order": 16
    },
    {
      "id": "T0017",
      "title": "자전거 팔기",
      "status": "미완료",
      "area": "집",
      "type": "할일",
      "list": "일반",
      "created_at": "2026-09-26",
      "due_at": "",
      "completed_at": "",
      "delegate": "",
      "note": "",
      "sort_order": 17
    },
    {
      "id": "T0018",
      "title": "어항 호수 길게 조정하기",
      "status": "보류",
      "area": "집",
      "type": "할일",
      "list": "일반",
      "created_at": "2026-09-04",
      "due_at": "",
      "completed_at": "",
      "delegate": "",
      "note": "",
      "sort_order": 18
    },
    {
      "id": "T0019",
      "title": "선유 애플워치 세팅해 주기",
      "status": "위임",
      "area": "가족",
      "type": "할일",
      "list": "일반",
      "created_at": "2026-09-26",
      "due_at": "",
      "completed_at": "",
      "delegate": "와이프",
      "note": "",
      "sort_order": 19
    },
    {
      "id": "T0020",
      "title": "비타비 크린 구매하기",
      "status": "미완료",
      "area": "건강",
      "type": "구매",
      "list": "일반",
      "created_at": "2026-09-24",
      "due_at": "",
      "completed_at": "",
      "delegate": "",
      "note": "",
      "sort_order": 20
    },
    {
      "id": "T0021",
      "title": "고무밴드 2개 구매하기",
      "status": "미완료",
      "area": "집",
      "type": "구매",
      "list": "다이소",
      "created_at": "2026-09-26",
      "due_at": "",
      "completed_at": "",
      "delegate": "",
      "note": "",
      "sort_order": 21
    },
    {
      "id": "T0022",
      "title": "선풍기망 3개 구입하기",
      "status": "미완료",
      "area": "집",
      "type": "구매",
      "list": "다이소",
      "created_at": "2026-09-26",
      "due_at": "",
      "completed_at": "",
      "delegate": "",
      "note": "",
      "sort_order": 22
    },
    {
      "id": "T0023",
      "title": "기포기 구매하기",
      "status": "보류",
      "area": "집",
      "type": "구매",
      "list": "다이소",
      "created_at": "2026-09-07",
      "due_at": "",
      "completed_at": "",
      "delegate": "",
      "note": "",
      "sort_order": 23
    },
    {
      "id": "T0024",
      "title": "곰팡이 제거제",
      "status": "미완료",
      "area": "대전집",
      "type": "구매",
      "list": "대전집",
      "created_at": "2026-09-26",
      "due_at": "",
      "completed_at": "",
      "delegate": "",
      "note": "",
      "sort_order": 24
    },
    {
      "id": "T0025",
      "title": "먼지밀대",
      "status": "미완료",
      "area": "대전집",
      "type": "구매",
      "list": "대전집",
      "created_at": "2026-09-26",
      "due_at": "",
      "completed_at": "",
      "delegate": "",
      "note": "",
      "sort_order": 25
    },
    {
      "id": "T0026",
      "title": "입시설명회 참석",
      "status": "미완료",
      "area": "가족",
      "type": "일정",
      "list": "일정",
      "created_at": "2026-09-22",
      "due_at": "2026-10-07T19:30:00+09:00",
      "completed_at": "",
      "delegate": "",
      "note": "Google Calendar 등록됨",
      "sort_order": 26
    }
  ],
  "logs": [
    {
      "id": "L0001",
      "activity": "정리/청소",
      "start_at": "",
      "end_at": "",
      "duration_min": 420,
      "category": "집안일",
      "note": "2026-09-26 10시간 정리 도전, 실제 약 7시간 진행"
    }
  ]
};
